### ISSUE TITLE
Triggered Full sync runs multiple times.

### ISSUE THREAD

**Issue by jakolars** [lithnet/miis-autosync#156]
We have an issue with our nightly triggers running duplicate full syncs. 
When we have one full sync triggered it runs 2 times.
Example of trigger where this is happening: 
![bilde](https://user-images.githubusercontent.com/3500014/47338823-93094a00-d699-11e8-9c99-094933bccb69.png)

This is naturaly making our nightly runs very ineffective.

**Comment by jakolars** [comment]
@ryannewington i have now sent the Logs to your email.

**Comment by ryannewington** [comment]
@jakolars Thanks for sending through the logs.

I have an idea of what is going on here. It's an interesting problem.

When the trigger is first registered, it works out the exact number of milliseconds until 5:00:00am. The trigger wakes up at that time, and fires off the job. Then it has to work out the number of milliseconds until the next time 5:00:00am occurs.

You will notice that the trigger actually fires at  4:59:59. What seems to have happened, is that your system clock has been 'corrected' back by a small amount. This is usually by the virtual machine guest integration tools, or the AD time sync protocol. This is totally normal, because computer clocks do drift. 

The problem it causes for us is that the trigger then has to work out when to fire next, so it's trying to work out "when is the next 5:00:00am", which happens to be only a few hundred milliseconds away by this point, so you get the trigger fired again.

This is a problem with autosync's scheduling logic. I'll need to look at another way to do this.

**Comment by ryannewington** [comment]
@jakolars 

Here is a build to test with and see if it resolves your issue.

[autosync.zip](https://github.com/lithnet/miis-autosync/files/2509962/autosync.zip)

@Manjunath-hk1 we'll need to deploy and test in our environment as well before an official release.

**Comment by jakolars** [comment]
@ryannewington wow, great speed!
Thank you so much, will test the new build today.

**Comment by Manjunath-hk1** [comment]
Thanks Ryan, Build has been deployed to developed. Initial run looks good. I will report if any issue.

**Comment by ryannewington** [comment]
@jakolars has this solve the issue for you?

**Comment by jakolars** [comment]
Hi,
we've have had it running for a week now. And it seems to work properly.  No problems.  Thanks so much for the quick fix.
