### ISSUE TITLE
PowerShell-Script Paramater

### ISSUE THREAD

**Issue by rschre** [lithnet/miis-autosync#166]
Hi there

First of all I like using your product very much!
Is there a way to pass Parameters to PowerShell-Scripts in the Triggers other than username/password?

Thank you and kind regards
Raffael

**Comment by ryannewington** [comment]
Hi @rschre

There isn't at the moment, but if you want to walk me though your use case I can advise if there's another way to do it or if we can add the functionality to the app.

Ryan

**Comment by rschre** [comment]
Hi Ryan

The idea was to pass the name of the management agent, on which the trigger
is defined to the script, so I can use the same script for multiple
managememt agents.
Or that I could use the same logic to check if exports are pending but
would be able to define different thresholds per MA.
Right now I'm judt using multiple scripts with hardcoded values.

Kind regards
Raffael


Ryan Newington <notifications@github.com> schrieb am Sa., 27. Juli 2019,
00:02:

**Comment by kcrosby** [comment]
I know this is already assigned/pinned, but I just wanted to add that I ran into the same thing. I have a client with several Oracle management agents that we just configured for Deltas using the Generic SQL connector, and now want to use a PowerShell trigger to avoid unnecessary delta imports. The script is 99% the same for each connector, so if we can pass parameters in we could get down to a single script.

**Comment by Niehweune** [comment]
Just wanted to add another use case to this one: 
We have >30 MA's doing the same thing for different systems (syncing data to multiple Azure tenants from one central source MA), but all using the same trigger script to check if we've got a recent full import.
Because of the massive amounts of objects, we're currently randomizing the full import runs (which isn't ideal).

An easy solution might be to set a global variable just before adding the Get-RunProfileToExecute command, just after:
https://github.com/lithnet/miis-autosync/blob/b983bd05fc4088a73606a1930ba3aff3dcf750bb/src/Lithnet.Miiserver.AutoSync/Triggers/PowerShellExecutionTrigger.cs#L116

Add something along the lines of
```
this.powershell
  .AddCommand("New-Variable")
  .AddParameter("Name","MAName")
  .AddParameter("Value",this.ManagementAgentName)
  .AddParameter("Scope","Global");
```

**Comment by ryannewington** [comment]
Hi all,

Here is a build to test.

Modify your function signature to the following

```
function Get-RunProfileToExecute($maname) 
{
...
}
```

If this meets your needs, I'll update the release build accordingly.

[autosync.zip](https://github.com/lithnet/miis-autosync/files/7188773/autosync.zip)

**Comment by Niehweune** [comment]
We've been able to test this version, and it looks like this works like a charm.

In our use case:

Defined the function as:

```
function Get-RunProfiletoExecute {
  param(
    [String]$maname
  )
 ...
}
```

Inside the function, retrieve RunHistory of the MA to see when the last full import has run and (depending on some business logic) trigger a new import when needed.

NB: haven't tested this for backward compatibility (i.e.: script without an empty param() block being called with a parameter), but I reckon pwsh will simply ignore the parameter then.

**Comment by ryannewington** [comment]
Added to release

https://github.com/lithnet/miis-autosync/releases/tag/v1.2.8002
