### ISSUE TITLE
"Add run profile to the front of the queue" for Full Sync issue

### ISSUE THREAD

**Issue by cormeister** [lithnet/miis-autosync#179]
I have scheduled full imports on all my MAs to run at the same time. What I am trying to do is to get a full sync on one of the MAs (called LDAP) to run immediately after all of the full imports are done. Once that full sync finishes, I would like to run full syncs on all of my other MAs (in any order) and then have autosync continue on it's normal process. 

The full imports are working great, but getting the LDAP full sync to run first is not. To try and get this working, I have enabled "Add run profile to the front of the queue" and "Run profile must be executed exclusively" just on the LDAP full sync. I have set a scheduled interval trigger for the full sync to start half an hour after the full imports start. The full imports all finish within about 3.5 hours, with the LDAP full import finishing last. 

Unfortunately, another full sync is starting before the LDAP full sync. I'm not sure if this is a bug or if it's me not understanding how the application works. Shouldn't "Add run profile to the front of the queue" make whatever run profile I've set that on run first after everything else has completed (full imports in my case)?

**Comment by ryannewington** [comment]
Hi @cormeister 

It's a little difficult to get my head around the whole scenario to accurately explain what is going on.

The 'add run profile to front of the queue' does set the job to run next, but any jobs that are already staged (eg have taken their locks) won't be bumped. It will move the job to start of the 'unstaged' job list, and it only applies to that MA, not across the entire set of waiting jobs.

For this specific case, I'd suggest creating a two-step run profile for that LDAP MA, Full import followed by full sync (note; not a combined one-step profile), and trigger that on your scheduled task instead. Autosync will have to wait for both tasks to complete before running other jobs.

If I havent understood correctly, some screen shots of the scheduled tasks, and the matching execution logs would be helpful in understanding the problem a bit more.

**Comment by cormeister** [comment]
Hi @ryannewington!

Thank you very much! I think that the two-step run profile may work for my problem. Do you know if I can run full imports from my other MAs at the same time or should I run the two-step run profile exclusively? I'm worried that if I run the two-step and other full imports at the same time, if those other full-imports aren't done and it gets to the Full Sync, it could cause an issue. 

Thank you!

**Comment by ryannewington** [comment]
AutoSync will never run profiles together that will conflict. The sync engine has very specific rules about what things must run exclusively and what may run concurrently. AutoSync is designed so you don't need to worry about that. You'll never be able to force it to break MIMs rules. 

The "Run exclusively" option is there for jobs that would normally be allowed the run concurrently (eg imports) but you'd like to run exclusively. 

In the case of your two step run profile, AutoSync will be forced to run this exclusively because it contains a sync step. All syncs run exclusively. Even through it had an import step in it, we can only launch the profile, not the individual steps, so we have to lock for the entire job. 

This is normally why we advise against using multi-step run profiles. It limits AutoSyncs ability to maximise throughput by forcing unnecessary use of exclusive locks.

However in this case, for your scheduled run, it's entirely appropriate and is going to behave exactly as we want it to for this specific situation.
