### ISSUE TITLE
Run execute multiple times within the scheduled period if it got lock by another run.

### ISSUE THREAD

**Issue by mwwessie** [lithnet/miis-autosync#181]
We have set our Delta Imports to run every 15 minutes for all our (19) MAs, but when one MA lock the runs for more than the 15 minutes it then place the next run in a queue which is as expected, but if the next scheduled run is still lock it add another run to the same queue which then run multiple times as per the amount of items in the queue and not just once until the next schedule. Could it be set/configure that only one run must be queued and if the runs are lock and the next schedule pass that it will still only have one run to execute?

**Comment by ryannewington** [comment]
@mwwessie 

You shouldn't be seeing any more than one staged DI plus one in the queue at any give them. So a maximum of two.

The reason for the 2, rather than 1, is that due to race conditions, we don't want to miss a DI request from a change notifier that may come in just after a DI has kicked off.

If you are seeing more than these two, can you share the log file so we can see whats going on

**Comment by mwwessie** [comment]
Thank you that make sense, as I see only "DI*,DI" in the log files and then when that runs the schedule occur for the next run which is then 3 runs in close succession.
